/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Spring.Logic;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        
        EndPointController test =new EndPointController();
        assertEquals("lists all inputs", test.getallInputs());
    }
}
